### ISSUE TITLE
code license absent

### ISSUE THREAD

**Issue by timabell** [lelandrichardson/BQL#1]
Hi, Thanks for the article and code, a noble goal indeed.

I don't see a choice of license for the code, which I think would be important to encourage contributions and reuse of your ideas. I suggest something with minimal restrictions like MIT or BSD.

**Comment by iCodeSometime** [comment]
This. The project is clearly abandoned, but legally no one is allowed to take it over since there's no license granting permission to distribute modifications.

cc @lelandrichardson

**Comment by lelandrichardson** [comment]
You are right, omitting a license was not intentional and I would love for anyone else to use these ideas to create something real.

I've added the MIT license to this repo. Hope that helps. Thanks.
